### ISSUE TITLE
your jenkins dashboard is open to internet no auth

### ISSUE THREAD

**Issue by gowtham-ujjineni** [Majekdor/PartyChat#43]
i am searching in shodan for something and i have seen your jenkins dashboard exposed. 

i am just trying to help you. 

YOUR JENKINS DASHBOARD IS OPEN IN INTERNET EXPOSED FOR EVERYONE

**Comment by Majekdor** [comment]
I don't see anything wrong with Jenkins at the moment. What do you mean by "dashboard"? Yes the dashboard is exposed, but you have to login to be able to do anything meaningful. If there is an actual security issue please message me on discord @Majekdor#6346 instead of on public GitHub.
